config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'week#index'

  resources :carts

  resources :shelvers

  resources :daily_logs, controller: 'daily_log'

  get '/:year/week/:week_number/day/:day_number' => 'week#show'

  get '/library-hours' => 'library_hours#index'

  get '/setup-wizard' => 'wizard#index'

  post '/setup-wizard' => 'wizard#import'

end

app/controllers/week_controller.rb
class WeekController < ApplicationController

	def index
		if params[(:week_number)] == nil
			# wday range: 0..6
			@day = DateTime.now.wday + 1
			get_date(@week, @day, @year)
			set_previous_next_link_variables
		end

		@day_symbol = DateTime.now.strftime("%a").downcase
		@schedules_this_week = Schedule.select{|sched| sched.week_number == @week}
		if @schedules_this_week.count > 0
			@shelvers = Schedule.select{|x| x.send(@day_symbol) != nil && x.week_number == @week}.map{|sched| sched.shelver}.sort_by{|s| s.last_name}
		end

	end

	def show
		if params[(:week_number)].to_i > 53 || params[(:week_number)].to_i < 1 || params[(:day_number)].to_i > 7 || params[(:day_number)].to_i < 1
			redirect_to root_path
		end

		if params[(:week_number)].to_i > 0 && params[(:week_number)].to_i < 54 && params[(:day_number)].to_i > 0 && params[(:day_number)].to_i < 8
			@week = params[(:week_number)].to_i
			@day = params[(:day_number)].to_i
			@year = params[(:year)].to_i
			get_date(@week, @day, @year)
			set_previous_next_link_variables_show
		end

		@day_symbol = Date.commercial(@year, @week, @previous_day).strftime("%a").downcase

		@shelvers = Schedule.select{|x| x.send(@day_symbol) != nil && x.week_number == @week}.map{|sched| sched.shelver}.sort_by{|s| s.last_name}
	end

	private

	def get_date(week, day, year)
		if week > 0 && week < 54 && day > -1 && day < 8
			if day == 1
				adj_day = 7
				adj_week = week - 1
			else
				adj_day = day - 1
				adj_week = week
			end
			date_instance = Date.commercial(year, adj_week, adj_day)
			@todays_date = date_instance.strftime("%A, %B #{date_instance.day.ordinalize}, %Y")
		end
	end

	def set_previous_next_link_variables
		if @day == 7
			@next_day = 1
			@next_week = @week + 1
		else
			@next_day = @day + 1
			@next_week = @week
		end

		if @week == 52 && @day == 7
			@next_week = 1
			@next_year = @year + 1
		else
			@next_year = @year
		end

		if @day == 1
			@previous_day = 7
			@previous_week = @week - 1
		else
			@previous_day = @day - 1
			@previous_week = @week
		end

		if @week == 1 && @day == 1
			@previous_week = 52 #bug
			@previous_year = @year - 1
		else
			@previous_year = @year
		end
	end

	def set_previous_next_link_variables_show
		if @day == 7
			@next_day = 1
			@next_week = @week + 1
		else
			@next_day = @day + 1
			@next_week = @week
		end

		if @week == 52 && @day == 7
			@next_week = 1
			@next_year = @year + 1
		else
			@next_year = @year
		end

		if @day == 1
			@previous_day = 7
			@previous_week = @week - 1
		else
			@previous_day = @day - 1
			@previous_week = @week
		end

		if @week == 1 && @day == 1
			@previous_week = 52
			@previous_year = @year - 1
		else
			@previous_year = @year
		end
	end

end

app/helpers/week_helper.rb
module WeekHelper
end

app/views/week/index.html.erb
<%= render 'menu' %>

<div class="container py-4">
	<div class="row">
		<div class="float-left">
			<h2>
			<a href="/<%= @previous_year %>/week/<%= @previous_week %>/day/<%= @previous_day %>"><i class="fas fa-arrow-alt-circle-left"></i></a> 
			<a href="/<%= @next_year %>/week/<%= @next_week %>/day/<%= @next_day %>"><i class="fas fa-arrow-alt-circle-right"></i></a> 
			<%= @todays_date %></h2>
		</div>
		<div class="ml-auto"><h2><a href="#"><i class="fas fa-user-edit" data-toggle="modal" data-target="#myModal"></i></a></h2></div>
	</div>
	<div class="row">
	<% if @week > 53 || @day > 7 || @week < 1 || @day < 1 %>
		<h3>Blue Screen</h3>
		<p>
			Invalid Date or Data Error<br>
			Week Number: <%= @week %>, Day Number: <%= @day %>
		</p>
	<% else %>
		<p>
			Week Number: <%= @week %>, Day Number: <%= @day %>
		</p>
	</div>
	<div class="row">

		<table border="1">
			<tr>
				<th>Shelver</th>
				<th>Hours Today</th>
				<th>Email</th>
				<th>Shelf<br>Reading</th>
				<th>Department</th>
				<th>Daily Tasks</th>
				<th>Cleanup</th>
				<th>#Carts Shelved</th>
				<th>#Carts Sorted</th>
				<th>&nbsp;</th>
			</tr>
		<% if @shelvers == nil %>
			<tr>
				<td colspan="10">No data</td>
			</tr>
		<% else %>
		<% @shelvers.each do |shelver| %>
			<tr>
				<% day_object = DateTime.now.strftime("%a").downcase %>
				<% daily_log = shelver.get_daily_log(shelver.id, @year, @week, @day) %>
				<td><%= link_to "#{shelver.last_name}, #{shelver.first_name}", shelver %></td>
				<td><%= shelver.schedules.last.send(day_object) %></td>
				<% if shelver.daily_logs.map{|dl| dl.year}.include?(@year) && shelver.daily_logs.map{|dl| dl.week_number}.include?(@week) && shelver.daily_logs.map{|dl| dl.day_number}.include?(@day) %>
				<td><i class="fas fa-exclamation-triangle"></i></td>
				<td></td>
				<td><%= daily_log.department %></td>
				<td><%= daily_log.daily_tasks %></td>
				<td><%= daily_log.cleanup %> (x-x)</td>
				<% else %>
				<td colspan="5"><i class="fas fa-exclamation-triangle"></i> No Daily Log found</td>
				<% end %>
				<td>{{ generated }}</td>
				<td>{{ generated }}</td>
				<td class="edit-icon">
					<% if shelver.daily_logs.map{|dl| dl.week_number}.include?(@week) && shelver.daily_logs.map{|dl| dl.day_number}.include?(@day) %>
					<%#= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_daily_log_path(shelver_id: shelver.id, day: @day),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#shelverModal'} %>
					<i class="fas fa-edit"></i>
					<% else %>
					<%= link_to '<i class="fas fa-plus-circle"></i>'.html_safe, new_daily_log_path(shelver_id: shelver.id, day: @day),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#shelverModal'}  %>
					<% end %>
				</td>
			</tr>
		<% end %>
		<% end %>
		</table>
	</div>

	<!-- The Modal -->
 	<div class="modal" id="myModal">
		<div class="modal-dialog">
			<div class="modal-content">

			<div class="modal-header">
				<h4 class="modal-title">Edit All Daily Tasks</h4>
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>

			<div class="modal-body">
				<% if @shelvers == nil %>
					<p>No Shelvers</p>
				<% else %>
				<% @shelvers.each do |shelver| %>
				<div class="pb-3">
					<h6 class="font-weight-bold"><%= shelver.last_name %></h6>
					<table>
					<%= form_for :daily_logs do |f| %>
						<%= f.hidden_field :shelver_id %>
						<%= f.hidden_field :year %>
						<%= f.hidden_field :week_number %>
						<%= f.hidden_field :day_number %>
						<tr>
							<td><%= f.label :department %>: </td>
							<td><%= f.select(:department, ['Fiction & Media', 'Reference', 'Youth Services']) %></td>
						</tr>
						<tr>
							<td><%= f.label :daily_tasks, "Daily Tasks" %>: </td>
							<td><%= f.select(:daily_tasks, ["Unpack RAILS bins", "Holds Pick-List Reference", "Holds Pick-List YS", "Holds Pick-List Fiction", "Holds Pick-List Media", "ILL Pick-List", "Missing/In-Transit/Claims Reports", "New Media", "New Reference", "New Fiction", "New Juv/YA"], {}, {class: "selectpicker", multiple: true}) %></td>
						</tr>
 						<tr>
							<td><%= f.label :cleanup %>: </td>
							<td><%= f.select(:cleanup, ['Fiction & Media', 'Reference', 'Youth Services', ['No Cleanup', '']]) %></td>
						</tr>
						<tr>
							<td><%= f.label :cleanup_early, "Early Cleanup" %>: </td>
							<td><%= f.check_box :cleanup_early %></td>
						</tr>						

						<%= f.submit "Create" %>
					<% end %>
					</table>
				</div>
				<% end %>
				<% end %>
			</div>

			<div class="modal-footer">
				<button type="button" class="btn btn-primary btn-sm" data-dismiss="modal">Submit</button>
			</div>

			</div>
		</div>
	</div>


	<div class="row">
		<!-- The Shelver's Modal -->
		<div id="shelverModal" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content"></div>
			</div>		
		</div>
	</div>




	<% end %>

	<div class="row">
	<p>
		<%= render 'notes' %>
	</p>
	</div>

</div>

app/views/week/show.html.erb
<%= render 'menu' %>

<div class="container py-4">
	<div class="row">
		<div class="float-left">
			<h2>
			<a href="/<%= @previous_year %>/week/<%= @previous_week %>/day/<%= @previous_day %>"><i class="fas fa-arrow-alt-circle-left"></i></a> 
			<a href="/<%= @next_year %>/week/<%= @next_week %>/day/<%= @next_day %>"><i class="fas fa-arrow-alt-circle-right"></i></a>
			<%= @todays_date %></h2>
		</div>
		<div class="ml-auto"><h2><a href=""><i class="fas fa-user-edit"></i></a></h2></div>
	</div>
	<div class="row">
	<% if @week > 53 || @day > 7 || @week < 1 || @day < 1 %>
		<h3>Blue Screen</h3>
		<p>
			Invalid Date or Data Error<br>
			Week Number: <%= @week %>, Day Number: <%= @day %>
		</p>
	<% else %>
		<p>
			Week Number: <%= @week %>, Day Number: <%= @day %>
		</p>
	</div>
	<div class="row">

		<table border="1">
			<tr>
				<th>Shelver</th>
				<th>Hours Today</th>
				<th>Email</th>
				<th>Shelf<br>Reading</th>
				<th>Department</th>
				<th>Daily Tasks</th>
				<th>Cleanup</th>
				<th>#Carts Shelved</th>
				<th>#Carts Sorted</th>
				<th></th>
			</tr>
		<% @shelvers.each do |shelver| %>
			<tr>
				<td><%= link_to "#{shelver.last_name}, #{shelver.first_name}", shelver %></td>
				<td><%= shelver.sched_for_day(@year, @week, @day_symbol) %></td>
				<% daily_log = shelver.show_daily_log(@year, @week, @day) %>

				<% if daily_log != nil %>
				<td><%= daily_log.email %></td>
				<td><%= daily_log.shelf_reading %></td>
				<td><%= daily_log.department %></td>
				<td><%= daily_log.daily_tasks %></td>
				<td><%= daily_log.cleanup %></td>
				<td>{{ generated }}</td>
				<td>{{ generated }}</td>
				<td class="edit-icon"><%= link_to '<i class="fas fa-info-circle"></i>'.html_safe, shelver %></td>
				<% else %>
				<td colspan="5"><i class="fas fa-exclamation-triangle"></i> No Daily Log found</td>
				<td>{{ generated }}</td>
				<td>{{ generated }}</td>
				<td class="edit-icon"><%= link_to '<i class="fas fa-info-circle"></i>'.html_safe, shelver %></td> 
				<% end %>

			</tr>
		<% end %>
		<% if @shelvers.count == 0 %>
			<tr>
				<td colspan="10">No data</td>
			</tr>
		<% end %>
		</table>
	</div>

	<% end %>

	<div class="row">
	<p>
		<%= render 'notes' %>
	</p>
	</div>

</div>