config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'week#index'

  resources :carts

  resources :shelvers

  resources :daily_logs, controller: 'daily_log'

  get '/:year/week/:week_number/day/:day_number' => 'week#show'

  get '/library-hours' => 'library_hours#index'

  get '/setup-wizard' => 'wizard#index'

  post '/setup-wizard' => 'wizard#import'

end

app/models/daily_log.rb
class DailyLog < ActiveRecord::Base
	belongs_to :shelver
end

app/controllers/daily_log_controller.rb
class DailyLogController < ApplicationController
	respond_to :html, :json

	def index
		@daily_logs = DailyLog.alle
	end

	def create
	    @daily_log = DailyLog.new(dl_params)
	    if @daily_log.save
	      redirect_to root_path
	    end
	end

	def new
		@shelver = Shelver.find(params[:shelver_id])
	    @daily_log = DailyLog.new
		@day = params[:day]
		respond_to do |format|
			format.html
			format.js
		end
  	end

  	def edit
  		@shelver = Shelver.find(params[:shelver].id)
  		@daily_log = DailyLog.find(params[:id])
  	end

	def update
  		@daily_log = DailyLog.find(params[:id])
		if @daily_log.update_attributes(dl_params)
			redirect_to root_path
		else
			redirect_to root_path
		end
	end


	private

	def dl_params
		params.require(:daily_log).permit(
			:email, :shelf_reading, :department, 
			:daily_tasks, :cleanup, :cleanup_early, 
			:cleanup_done, :carts_sorted, :year, 
			:week_number, :day_number, :shelver_id
		)
	end

end

app/helpers/daily_log_helper.rb
module DailyLogHelper
end

app/views/daily_log/_edit.html.erb
<div class="modal-header">
   <h3 id="myModalLabel">Add Daily Tasks</h3>
 </div>
<%= form_for(@daily_log) do |f| %>
 <div class="modal-body">
	<p><%= @shelver.first_name %> <%= @shelver.last_name %></p>
	<div class="actions">
	<table>
	<tbody>
		<%= f.hidden_field :shelver_id, value: @shelver.id %>
		<%= f.hidden_field :year, value: @year %>
		<%= f.hidden_field :week_number, value: @week %>
		<%= f.hidden_field :day_number, value: @day %>
		<tr><td>Department:</td><td><%= text_field :daily_log, :department %></td></tr>
		<tr><td>Daily Tasks:</td><td><%= text_field :daily_log, :daily_tasks %></td></tr>
		<tr><td>Cleanup:</td><td><%= text_field :daily_log, :cleanup %></td></tr>
	<!-- <tr><td></td><td><%#= link_to '<i class="fa fa-ban"></i>'.html_safe, @daily_log %> <%#= link_to '<i class="fa fa-list"></i>'.html_safe, daily_log_path %></td></tr>
	<tr><td>URL</td><td><%#= text_field :daily_log, :url %></td></tr>
	<tr><td valign="top"><p>Description</p></td><td><%#= text_area :daily_log, :description, maxlength: 40 %></td></tr> -->
	<!-- <tr><td></td><td><div id="charNum"><span>40</span> characters left</div><%= f.submit %>&nbsp;&nbsp;<%#= link_to 'Cancel', @cat %></td></tr> -->
	</tbody>
	</table>
	</div>

 </div>
 <div class="modal-footer">
   <button class="btn" class="close" data-dismiss="modal">Cancel</button>
   <%= f.submit class: "btn btn-primary" %>
 </div>
<% end %>

app/views/daily_log/_new.html.erb
<div class="modal-header">
   <h3 id="myModalLabel">Add Daily Tasks</h3>
 </div>
 <div class="modal-body">
   <%= @shelver.first_name %> <%= @shelver.last_name %>
 </div>
 <div class="modal-footer">
   <button class="btn" class="close" data-dismiss="modal">Cancel</button>
   <button class="btn btn-primary">Add</button>
 </div>

app/views/daily_log/edit.js.erb
$("#shelverModal").find(".modal-content").html("<%= j (render 'edit') %>");
$("#shelverModal").modal();

app/views/daily_log/new.js.erb
$("#shelverModal").find(".modal-content").html("<%= j (render 'new') %>");
$("#shelverModal").modal();