config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'week#index'

  resources :carts

  resources :shelvers

  resources :daily_logs, controller: 'daily_log'

  get '/:year/week/:week_number/day/:day_number' => 'week#show'

  get '/library-hours' => 'library_hours#index'

  get '/setup-wizard' => 'wizard#index'

  post '/setup-wizard' => 'wizard#import'

end

app/models/shelver.rb
class Shelver < ActiveRecord::Base
	has_many :schedules
	has_many :daily_logs
	has_many :cart_contents
	accepts_nested_attributes_for :daily_logs

	def show_daily_log(year, week, day)
		daily_logs.find_by(year: year, week_number: week, day_number: day)
	end

	def sched_for_day(year, week, day)
		schedules.find_by(year: year, week_number: week).send(day)
	end

	def get_daily_log(shelver_id, year, week, day)
		DailyLog.where(
			shelver_id: shelver_id,
			year: year,
			week_number: week,
			day_number: day
		)[0]
	end
end

app/controllers/shelvers_controller.rb
class ShelversController < ApplicationController

	def index
		@shelvers = Shelver.select{|shelver| shelver.last_day == nil}.sort_by {|shelver| shelver.last_name }
		@past_shelvers = Shelver.select{|shelver| shelver.last_day != nil}.sort_by {|shelver| shelver.last_name }
		# if (DateTime.now+1.day).cweek == (DateTime.now).cweek + 1
		# 	@week = DateTime.now.cweek + 1
		# else
		# 	@week = DateTime.now.cweek
		# end
		# @year = DateTime.now.strftime("%Y").to_i

		# @start_of_week = (DateTime.commercial(@year, @week, 1)-1.day).strftime("%b %-d, %Y")
		# @end_of_week = DateTime.commercial(@year, @week, 6).strftime("%b %-d, %Y")
	end

	def show
		@shelver = Shelver.find(params[:id])
	end

	def new
		@shelver = Shelver.new
	end

	def create
		@shelver = Shelver.new(shelver_params)
		# @shelver.user = current_user
		if @shelver.save
		  redirect_to @shelver
		else
		  render action: 'new'
		end
	end

	def shelvers_open_modal
		@shelver = Shelver.find(params[:shelver_id])
		respond_to do |format|
			format.js
		end
	end

	private

	def shelver_params
		params.require(:shelver).permit(:first_name, :last_name)
	end

end

app/helpers/shelvers_helper.rb
module ShelversHelper
end

app/views/shelvers/_form.html.erb
  
  <%# if @shelver.errors.any? %>
    <div class="bgError">
      <%# @shelver.errors.full_messages.each do |msg| %>
        <%#= msg %><br>
      <%# end %>
    </div>
  <%# end %>
<%= form_for(@shelver) do |f| %>
  <div class="actions">
    <table class="new-edit">
      <tbody>
        <tr><td></td><td><%= link_to '<i class="fa fa-ban"></i>'.html_safe, @shelver %> <%= link_to '<i class="fa fa-list"></i>'.html_safe, shelvers_path %><% if !current_page? new_shelver_path %> <%= link_to '<i class="fa fa-trash"></i>'.html_safe, @shelver, method: :delete, data: { confirm: 'Are you sure?' } %><% end %></td></tr>
        <tr><td>First Name</td><td><%= text_field :shelver, :first_name %></td></tr>
        <tr><td>Last Name</td><td><%= text_field :shelver, :last_name %></td></tr>
        <tr><td></td><td><%= f.submit %>&nbsp;&nbsp;<%= link_to 'Cancel', @shelver %></td></tr>
      </tbody>
    </table>
  </div>
<% end %>

app/views/shelvers/index.html.erb
<%= render 'menu' %>

<div class="container py-4">
	<div class="row">
		<div class="float-left">
			<h1>All Shelvers: Week #<%= @week %></h1>
		</div>
		<div class="ml-auto">
			<h1><a href="#"><i class="far fa-calendar-alt"></i></a></h1>
		</div>
	</div>
	<div class="row">
		<table border="1">
			<tr>
				<th rowspan="2">Name <%= link_to '<i class="fas fa-user-plus"></i>'.html_safe, new_shelver_path %></th>
				<th rowspan="2">Current</th>
				<th colspan="7">Schedule: <%= @start_of_week %>-<%= @end_of_week %></th>
				<th rowspan="2">Total Hours</th>
				<th rowspan="2"></th>
			</tr>
			<tr>
				<td>Sun</td>
				<td>Mon</td>
				<td>Tue</td>
				<td>Wed</td>
				<td>Thu</td>
				<td>Fri</td>
				<td>Sat</td>
			</tr>
			<% @shelvers.each do |shelver| %>
				<% current_schedule = shelver.schedules.last %>
			<tr>
				<td><%= link_to "#{shelver.last_name}, #{shelver.first_name}", shelver %></td>
				<td><% if @week == current_schedule.week_number.to_i %><i class="fas fa-check-circle"></i><% else %><i class="fas fa-times-circle"></i><% end %></td>
				<td><%= current_schedule.sun if current_schedule != nil %></td>
				<td><%= current_schedule.mon if current_schedule != nil %></td>
				<td><%= current_schedule.tue if current_schedule != nil %></td>
				<td><%= current_schedule.wed if current_schedule != nil %></td>
				<td><%= current_schedule.thu if current_schedule != nil %></td>
				<td><%= current_schedule.fri if current_schedule != nil %></td>
				<td><%= current_schedule.sat if current_schedule != nil %></td>
				<td><%= current_schedule.total_hours %></td>
				<td class="edit-icon"><%= link_to '<i class="fas fa-edit"></i>'.html_safe, shelver %></td>
			</tr>
			<% end %>
			<tr><td colspan="11" bgcolor="#e0e0e0" style="font-weight: bold;">Archived Shelvers</td></tr>
			<% @past_shelvers.each do |shelver| %>
				<tr>
					<td><%= link_to "#{shelver.last_name}, #{shelver.first_name}", shelver %></td>
					<td colspan="9"></td>
					<td class="edit-icon"><%= link_to '<i class="fas fa-edit"></i>'.html_safe, shelver %></td>
				</tr>
			<% end %>
		</table>
	</div>
	<div class="row">
		<p><hr></p>
		<p><%= image_tag("/images/shelf_reading.jpg", style: "width: 50%;") %></p>
		<p><hr></p>
	</div>
</div>

<!-- <h3>Static Table</h3>

<table border="1">
	<tr>
		<th>ID</th>
		<th>Name</th>
		<th colspan="7">Schedule This Week</th>
		<th>Total Hours</th>
		<th></th>
	</tr>
	<tr>
		<td>1</td>
		<td>Inna Malamud</td>
		<td>12-4</td>
		<td>8-1</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td>8-1</td>
		<td>{{ calculated }}</td>
		<td><a href=""><i class="fas fa-edit"></i></a></td>
	</tr>
	<tr>
		<td>2</td>
		<td>Jane Voronova</td>
		<td>12-5</td>
		<td>8-12</td>
		<td></td>
		<td></td>
		<td></td>
		<td>8-12</td>
		<td>8-1</td>
		<td>{{ calculated }}</td>
		<td><a href=""><i class="fas fa-edit"></i></a></td>
	</tr>
	<tr>
		<td>3</td>
		<td>Stephanie Mayer</td>
		<td></td>
		<td></td>
		<td>1130-430</td>
		<td>1130-530</td>
		<td>1130-530</td>
		<td>1130-530</td>
		<td>1130-430</td>
		<td>{{ calculated }}</td>
		<td><a href=""><i class="fas fa-edit"></i></a></td>
	</tr>
	<tr>
		<td>4</td>
		<td>Paul McDonald</td>
		<td></td>
		<td>3-9</td>
		<td>3-9</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td>{{ calculated }}</td>
		<td><a href=""><i class="fas fa-edit"></i></a></td>
	</tr>
	<tr>
		<td>5</td>
		<td>Matt McGill</td>
		<td></td>
		<td></td>
		<td></td>
		<td>1-5</td>
		<td>1-5</td>
		<td>1-5</td>
		<td>11-5</td>
		<td>{{ calculated }}</td>		
		<td><a href=""><i class="fas fa-edit"></i></a></td>
	</tr>
	<tr>
		<td>6</td>
		<td>Arman Talaefard</td>
		<td>12-4</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td>8-4</td>
		<td>8-4</td>
		<td>{{ calculated }}</td>
		<td><a href=""><i class="fas fa-edit"></i></a></td>
	</tr>
	<tr>
		<td>7</td>
		<td>Patrick Villanueva</td>
		<td>12-5</td>
		<td></td>
		<td>1245-545</td>
		<td></td>
		<td>830-530</td>
		<td></td>
		<td></td>
		<td>{{ calculated }}</td>
		<td><a href=""><a href=""><i class="fas fa-edit"></i></a></a></td>
	</tr>
	<tr>
		<td>8</td>
		<td>Beth Grossman</td>
		<td></td>
		<td>1-6</td>
		<td>1-6</td>
		<td></td>
		<td></td>
		<td>1-5</td>
		<td>1-5</td>
		<td>{{ calculated }}</td>
		<td><a href=""><i class="fas fa-edit"></i></a></td>
	</tr>	

	<tr>
		<td>9</td>
		<td>Maria Petrova</td>
		<td></td>
		<td>4-8</td>
		<td></td>
		<td></td>
		<td>4-8</td>
		<td></td>
		<td>11-3</td>
		<td>{{ calculated }}</td>
		<td><a href=""><i class="fas fa-edit"></i></a></td>
	</tr>
	<tr>
		<td>10</td>
		<td>Sunkyung Lee</td>
		<td>12-4</td>
		<td>8-1</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td>8-1</td>
		<td>{{ calculated }}</td>
		<td><a href=""><i class="fas fa-edit"></i></a></td>
	</tr>
	<tr>
		<td>11</td>
		<td>Paul Kim</td>
		<td>1-5</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td>8-12</td>
		<td>{{ calculated }}</td>		
		<td><a href=""><i class="fas fa-edit"></i></a></td>
	</tr>
	<tr>
		<td></td><td colspan="10"><a href="">+New Shelver</a></td>
	</tr>
</table> -->

app/views/shelvers/new.html.erb
<%= render 'menu' %>

<h1>Add Shelver</h1>

<div id="formContainer">
<%= render 'form' %>

</div>

app/views/shelvers/show.html.erb
<%= render 'menu' %>

<h2><%= @shelver.first_name %> <%= @shelver.last_name %></h2>

<p>Schedule This Week:</p>
<% sched = @shelver.schedules.last %>
<table border="1">
	<tr>
		<th>Sun</th>
		<th>Mon</th>
		<th>Tue</th>
		<th>Wed</th>
		<th>Thu</th>
		<th>Fri</th>
		<th>Sat</th>
	</tr>
	<tr>
		<td><%= sched.sun if sched != nil %></td>
		<td><%= sched.mon if sched != nil %></td>
		<td><%= sched.tue if sched != nil %></td>
		<td><%= sched.wed if sched != nil %></td>
		<td><%= sched.thu if sched != nil %></td>
		<td><%= sched.fri if sched != nil %></td>
		<td><%= sched.sat if sched != nil %></td>
	</tr>			
</table>

<p><hr /></p>

<p>Last Reading (Static Table)</p>
<table border="1">
	<tr><th>January 2020 Assignment</th><th>Last Read</th></tr>
	<tr><td>Board Books, Picture Books A-L</td><td>Agee - Lichtenstein</td></tr>
</table>