config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'week#index'

  resources :carts

  resources :shelvers

  resources :daily_logs, controller: 'daily_log'

  get '/:year/week/:week_number/day/:day_number' => 'week#show'

  get '/library-hours' => 'library_hours#index'

  get '/setup-wizard' => 'wizard#index'

  post '/setup-wizard' => 'wizard#import'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	before_action :authenticate_user!, :set_variables

	def set_variables
		if (DateTime.now+1.day).cweek == (DateTime.now).cweek + 1
			@week = DateTime.now.cweek + 1
		else
			@week = DateTime.now.cweek
		end
		@year = DateTime.now.strftime("%Y").to_i

		@start_of_week = (DateTime.commercial(@year, @week, 1)-1.day).strftime("%b %-d, %Y")
		@end_of_week = DateTime.commercial(@year, @week, 6).strftime("%b %-d, %Y")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_menu.html.erb
<ul class="nav">
	<li><%= link_to "Home", root_path %></li>
	<li><%= link_to "All Carts", carts_path %></li>
	<li><%= link_to "All Shelvers", shelvers_path %></li>
	<!-- <li><a href="#">All Clerks</a></li> -->
	<li><a href="#">Shelf Reading</a></li>
	<li><%= link_to "Library Hours", library_hours_path %></a></li>
	<li><%= link_to "Setup Wizard", setup_wizard_path %></li>
	<li><a href="#">Settings</a></li>
</ul>

app/views/application/_notes.html.erb
<!-- <p>day test symbol: <%= @test %></p> -->
<div>

<table class="notes">
	<tr>
		<td>
			<h4>Feature Punchlist</h4>

			<ol>
				<li class="crossout">Setup Wizard (Weekly)</li>
				<li class="crossout">implement csv schedule</li>
				<li>App Settings</li>
				<li>Completed Carts</li>
				<li>Partial Carts</li>
				<li>Shelf Reading</li>
				<li>Real-Time highlighting/updates</li>
				<li>create PDF of view</li>
				<li>Integrate Volunteer (Mary)</li>
				<li>email</li>
				<li>weekly report</li>
			</ol>

			<ul>
				<li>Bunch of stats here, graphs, etc.
					<ul>
						<li>stat: filled carts today</li>
						<li>stat: sorted carts today</li>
						<li>stat: finished carts today</li>	
					</ul>
				</li>
				<li>Each shelver should have a stat page
					<ul>
						<li>stat: department count</li>
						<li>stat: daily tasks list count</li>
						<li>stat: cleanup count</li>
						<li>stat: cleanup early</li>
						<li>stat: percentage of email</li>
						<li>stat: percentage of shelf reading</li>
					</ul>
				</li>
			</ul>			
		</td>
		<td>
			<h4>Shelvers Punchlist</h4>

			<ul>
				<li>Show Shelver
					<ul>
						<li>this week's schedule</li>
						<li>finished carts</li>
						<li>current carts</li>
						<li>history/trends
							<ul>
								<li>show assigned department count</li>
								<li>show cleanup count by department</li>
								<li>show assigned daily tasks count</li>
								<li>show finished carts count</li>
								<li>show sorted carts count</li>
							</ul>
						</li>
						<li>calculate speed: carts/hour</li>
					</ul>
				</li>
				<li>Edit Shelver</li>
				<li>Delete/Deactivate Shelver</li>
				<li>Add Active attribute</li>
			</ul>

		</td>
		<td>
			<h4>Notes</h4>

			<ol>
				<li>Add to Daily Tasks
					<ul>
					<li class="crossout">Unpack RAILS bins</li>
					<li class="crossout">ILL Pick-List</li>
					</ul>
				</li>
			</ol>

			<hr>

			<h4>Bugs</h4>

			<ul>
				<li>shelver checkmark for current hours buggy (when adding new shelver)</li>
				<li>total shelver/clerk hours when not :00 involved</li>
				<li>Beginning of year, week 1/day 1 (2020)</li>
				<li>End of year, week 53 (2020)</li>
				<li>week params > 53, day params < 1 won't redirect</li>
			</ul>

			<hr>

			<h4>Refactor</h4>

			<ul>
				<li class="crossout">week#show view</li>
				<li>week#index view</li>
				<li>redo shelver hour logic to match library hours</li>
			</ul>

		</td>
	</tr>
</table>
<table class="notes">
	<tr>
		<td colspan="2"><hr></td>
	</tr>
	<tr>
		<td style="width: 60%;">
			<p><%= image_tag("/images/shelvers_schedule.jpg", class: "fpo") %></p>			
		</td>
		<td style="width: 40%;">
			<h2>ipad app should...</h2>
			<ul>
				<li>show completed carts per shelver + #carts sorted</li>
				<li>show daily task list</li>
				<li>show cleanup schedule</li>
			</ul>

			<hr>

			<h3>Danny's Requests...</h3>
			<ul>
				<li>Reassignment for daily tasks (i.e. someone calls in sick)</li>
				<li>Cart list sorted by importance</li>
				<li class="crossout">Daily History: month's worth?</li>
			</ul>
			<hr>

			<h3>Notes from Diane</h3>
			<ul>
				<li>Time to fill cart: does not need to include shelver hours
					<ul>
						<li>from fill start to shelving end</li>
						<li>Factor in when shift ends (default)</li>
					</ul>
				</li>
				<li>Day Started/Day Ended - span</li>
				<li>Take note of Sunday opening</li>
			 </ul>

		</td>
	</tr>
</table>
<table class="notes">
	<tr>
		<td colspan="3">
			<hr>

			<p>(time_diff / 1.minute).round</p>
			<p>Week number: Time.now.strftime("%U").to_i<br>Week Numbers span 0-52</p>
			<p>Select Shelvers for the day => Shelver.all.select{|x| x if x.schedules[0].mon != nil}.map{|y| y.first_name}</p>
			<p>string to method => .send(string)</p>
			<p>Date.commercial(2020, 1, 1) => Mon, 30 Dec 2019</p>
			<p>string to object => x.to_sym</p>			
		</td>
	</tr>
 </table>

</div>